[features]
seeds = false
skip-lint = false
[programs.mainnet]
raffle = "DYUw8M1XatBe8NTAqJRuVWFVfFbS2GMEesS68wMsokDH"
auction = "66Eid29SYKM64KLC2fsnnCZ12YJNACiJRnfhhVui3d3u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "/home/admin-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
